export const ErrorMessageMapping: Record<string, string> = {
  ["INVALID_CREDENTIALS"]: "Invalid username or password",
  ["MISSING_COOKIE"]: "Cookie is missing",
  ["EXPIRED_REFRESH_TOKEN"]: "Session has expired",
  ["INVALID_REFRESH_TOKEN"]: "Session is invalid",
  ["INVALID_USER_FORMAT"]: "User has an invalid format",
  ["USERNAME_ALREADY_REGISTERED"]: "User already registered with this username",
  ["EMAIL_ALREADY_REGISTERED"]: "User already registered with this email",
  ["INVALID_USER"]: "User is invalid",
  ["PATIENT_ALREADY_REGISTERED"]: "Patient with same CNP already exists",
  ["FAMILY_DOCTOR_HAS_MAX_PATIENTS"]: "Selected Family doctor already has maximum number of patients",
  ["FAMILY_DOCTOR_REQUEST_ALREADY_EXISTS"]: "A family doctor request with this patient and family doctor already exists",
  ["FORBIDDEN"]: "Access is not allowed",
  ["INVALID_DATA"]: "Data is invalid",
};
